name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # This workflow will build a Java project with Gradle
    # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Jar file
        run: ./gradlew bootJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: kafka-demo-0.0.1-SNAPSHOT.jar
          path: ${{ github.workspace }}/build/libs/kafka-demo-0.0.1-SNAPSHOT.jar
          if-no-files-found: error
